### PR TITLE
feat(components, ui): Updates to the Main Menu Links

### PR DESCRIPTION
**Pull request by VancheeZze**
## Changes
- When a link value is removed, the field returns to the initial state.

## Test Instructions
See https://github.com/johnsonandjohnson/Bodiless-JS/issues/593

## Related Issues
Closes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/593

### CODE REVIEW

**Review by dewen — DISMISSED** [review]

**Comment by TatsianaMiraniuk** [comment]
@VancheeZze ,

please see **issue_1:**
Item label is removed if 'Remove Link' is clicked.

**Steps to Reproduce:**
1. add an item in MainMenu
2. add some text in i, e.g. 'item 1'
3. open Link form for the item
4. add a url in the field
5. click V
6. Reopen Link form for same item
7.  Click 'Remove Link'

**Expected Results:**
Link field _only_ is cleared and gets its initial placeholder '/link'

**Actual Result:**
the whole item get cleared - Item label is removed too.

**Comment by TatsianaMiraniuk** [comment]
@schristodoulou , @wodenx , @VancheeZze 

From the original story #593 

```
[This part will now be done in #499]
~~AC. The link icon label is replaced to "Edit" when there is a link, 

AND

"Add" when there is not a link~~
```

However it does not work as stated after implementing #499 - for Main Menu it always says 'Edit' even if a link wasn't set yet.

Question is - is that needed to be fixed in the current story?

**Comment by VancheeZze** [comment]
> @schristodoulou , @wodenx , @VancheeZze
> 
> From the original story #593
> 
> ```
> [This part will now be done in #499]
> ~~AC. The link icon label is replaced to "Edit" when there is a link, 
> 
> AND
> 
> "Add" when there is not a link~~
> ```
> 
> However it does not work as stated after implementing #499 - for Main Menu it always says 'Edit' even if a link wasn't set yet.
> 
> Question is - is that needed to be fixed in the current story?

I think since this issue is reproduced in the ond deprecated `rc-menu` we should not spend much time on trying to fix this issue.

cc: @TatsianaMiraniuk

**Comment by VancheeZze** [comment]
> @VancheeZze ,
> 
> please see **issue_1:**
> Item label is removed if 'Remove Link' is clicked.
> 
> **Steps to Reproduce:**
> 
> 1. add an item in MainMenu
> 2. add some text in i, e.g. 'item 1'
> 3. open Link form for the item
> 4. add a url in the field
> 5. click V
> 6. Reopen Link form for same item
> 7. Click 'Remove Link'
> 
> **Expected Results:**
> Link field _only_ is cleared and gets its initial placeholder '/link'
> 
> **Actual Result:**
> the whole item get cleared - Item label is removed too.

This issue is Fixed.

**Review by dewen — APPROVED** [review]

**Review by dewen — APPROVED** [review]

**Review by TatsianaMiraniuk — APPROVED** [review]

**Pull request merged**
