### PR TITLE
fix(carousel): carousel remediation

### PR DESCRIPTION
**Pull request by beliayeu**
## Changes
* fix: console warning on /carousel test-site page load and carousel navigation
* fix: disabled navigation button styles
* fix: horizontal card styles in chameleon carousel
* chore: added a carousel example with infinitive loop

### CODE REVIEW

**Review by hvanyo — DISMISSED** [review]

**Review by SW999 — DISMISSED** [review]

**Comment by irkhodzka** [comment]
issue 1:
Both navigation button or "Back" navigation button disappear on /flow-container-rtl carousel
**STR**:
1. Go to the /flow-container-rtl/
2. Add carousel component
3. Add 1 or more slided to the carousel
4. Observe Navigation buttons

**Actual Result**: Navigation button appear on limited time period when slides are switched
**Expected Result**: Navigation buttons are always visible to user

https://user-images.githubusercontent.com/81805756/116858301-d481f500-ac06-11eb-872f-294b7b3bdb35.mp4

5. Swap carousel to Horizontal Card view.
6. Add 1 or more slides in addition to existing one.
7. Observe navigation buttons
**Actual Result**: There is only "Next" button exists. "Back" button becomes visible for a limited time period whed slides are switched
**Expected Result**: Both "Back" and "Next" navigation buttons are always visible


https://user-images.githubusercontent.com/81805756/116858309-d8ae1280-ac06-11eb-8b58-6fecf6f76c36.mp4

**Comment by irkhodzka** [comment]
issue 2.
Carousel overlaps main menu items on flow-container-rtl
STR:
1. Go to the /flow-container-rtl/
2. Add carousel to the first or second flow container
3. Hover cursor over "Core" or "Component" menu items
4. Observe drop-down menu

**Actual Result:** Menu is hidden behind carousel
carousel-overlaps-menu

**Expected Result**: Menu is shown above carousel

_Note_: Google Chrome is up to date
Version 90.0.4430.93

**Review by SW999 — APPROVED** [review]

**Comment by irkhodzka** [comment]
Please find below the descriptionf of the
**issue 3**
Editing Title or Body text in HorizontalCard carousel without its preliminary stop leads to its rotation in the process of editing.

**STR**:
1. Go to the flow-container in edit env edit mode
2. Add carousel component -> swap it to HorizontalCard view.
3. Start editing Body text, Title without preliminary carousel stop.
4. Observe carousel behavior during typing.

**Expected Result**: Carousel stops rotation when user is typing text

https://user-images.githubusercontent.com/81805756/116983603-fa74cb80-acd2-11eb-979f-afe69167e2db.mp4

**Actual Result:** Carousel continues rotation despite user is typing text. The text is entered even when there is another slide shown.

**Review by SW999 — APPROVED** [review]

**Review by hvanyo — APPROVED** [review]

**Comment by hvanyo** [comment]
Approving because @irkhodzka  didn't have access at time she passed testing.

**Pull request merged**
