### PR TITLE
fix(organisms): Fix Menu item overlap after mouseover

### PR DESCRIPTION
**Pull request by VancheeZze**
## Changes
- Fixed an issue when clicking a top menu item in preview/static lead to submenus stay open.
- Submenus are no longer automatically shown on `focus` instead 'space' or `enter` key has to be pressed to open a submenu.
- Better accessibility that follows best practices defined by w3.org [here](https://www.w3.org/WAI/tutorials/menus/flyout/).

## Test Instructions
- Confirm submenus don't stay open on top menu item click/focus in Preview/Static mode.
- Confirm submenus may be opened by pressing `space` or `enter` keys when a top menu item is focused.

## Related Issues
Closes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/762

### CODE REVIEW

**Review by beliayeu — DISMISSED** [review]

**Comment by TatsianaMiraniuk** [comment]
Hi @VancheeZze ,

please find issues/questions below:

issue_1:
Submenus stay opens after navigating the Menu using Tab key
Steps to reproduce:
1. using Tab key, go to a Top Menu item with a submenu
2. Press 'Enter' (or Space) to open the submenu
3. using Tab key go to the next Top Menu item that has a submenu
4. Press 'Enter' (or Space) to open the submenu
Actual Results: first submenu still stays open even if a focus is no more in its area

**Comment by TatsianaMiraniuk** [comment]
@VancheeZze 

**issue_2:**
Placeholder text shifted to the right in Top Menu item, please see screenshot:
Screen Shot 2021-01-05 at 1 14 01 PM

**Comment by VancheeZze** [comment]
> @VancheeZze
> 
> **issue_2:**
> Placeholder text shifted to the right in Top Menu item, please see screenshot:
> Screen Shot 2021-01-05 at 1 14 01 PM

Fixed

**Comment by TatsianaMiraniuk** [comment]
@VancheeZze 

**issue_3:**

Tout/Column submenus are broken if they open by Enter/Space, please see screenshot

_Steps to reproduce:_
1. using Tab key, go to a Top Menu item with a Tout/Column submenu
2. press 'Enter' (or Space) to open the submenu
asdf

**Comment by VancheeZze** [comment]
> @VancheeZze
> 
> **issue_3:**
> 
> Tout/Column submenus are broken if they open by Enter/Space, please see screenshot
> 
> _Steps to reproduce:_
> 
> 1. using Tab key, go to a Top Menu item with a Tout/Column submenu
> 2. press 'Enter' (or Space) to open the submenu
>    asdf

Fixed

**Comment by TatsianaMiraniuk** [comment]
@VancheeZze ,

**issue_4:**
Menu item that has a link and currently is in focus doesn't have a 'focus' frame. Frame is visible only for Menu items without a link.

**Comment by VancheeZze** [comment]
> @VancheeZze ,
> 
> **issue_4:**
> Menu item that has a link and currently is in focus doesn't have a 'focus' frame. Frame is visible only for Menu items without a link.

This issue is caused by the `overflow-hidden` class on the menu item ( to hide submenus ). Blue outline border is there, but since it is not considered a border -- it is outside the component and thus hidden by `overflow-hidden`.

The issue is currently reproducible in master. It is hidden by the '<li>' element that gets focus though. If you try to set focus state to the <a> element directly through the chrome elements tab you won't see the blue outline either. It is incorrect `tabindex="0"` on the <li> element.

**Review by beliayeu — APPROVED** [review]

**Review by TatsianaMiraniuk — APPROVED** [review]

**Pull request merged**
